import mongoose from "mongoose";
import Recipe from "./models/recipe.model.js";
import dotenv from "dotenv";

dotenv.config();

const recipes = [
  {
    name: "Butter Chicken",
    cuisine: "Indian",
    image: "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
    ingredients: [
      "500g boneless chicken",
      "2 tbsp butter",
      "1 cup tomato puree",
      "1/2 cup heavy cream",
      "1 tbsp ginger-garlic paste",
      "1 tsp garam masala",
      "1 tsp red chili powder",
      "Salt to taste",
      "1/2 cup yogurt",
      "1 tbsp kasuri methi",
    ],
    instructions: [
      "Marinate chicken with yogurt, ginger-garlic paste, salt, and spices for 1 hour.",
      "Grill or pan-fry the chicken until slightly charred.",
      "Heat butter in a pan, add tomato puree, cook until thickened.",
      "Add grilled chicken, heavy cream, and kasuri methi, simmer for 10 minutes.",
      "Serve hot with naan or rice.",
    ],
  },
  {
    name: "Paneer Butter Masala",
    cuisine: "Indian",
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    ingredients: [
      "250g paneer (cubed)",
      "2 tbsp butter",
      "1 cup tomato puree",
      "1/2 cup heavy cream",
      "1 tbsp ginger-garlic paste",
      "1 tsp garam masala",
      "Salt to taste",
      "1 tbsp honey",
      "1 tbsp kasuri methi",
    ],
    instructions: [
      "Heat butter in a pan, sauté ginger-garlic paste until fragrant.",
      "Add tomato puree, cook until thickened.",
      "Stir in garam masala, salt, honey, and kasuri methi.",
      "Add paneer cubes and heavy cream, simmer for 10 minutes.",
      "Serve with roti or naan.",
    ],
  },
  {
    name: "Chicken Biryani",
    cuisine: "Indian",
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    ingredients: [
      "2 cups basmati rice",
      "500g chicken",
      "1 cup yogurt",
      "2 onions (sliced)",
      "1 tsp saffron",
      "1 tbsp biryani masala",
      "Salt to taste",
      "1/4 cup chopped coriander",
    ],
    instructions: [
      "Marinate chicken with yogurt, salt, and spices for 2 hours.",
      "Cook rice until 70% done, drain and set aside.",
      "Fry onions until golden brown.",
      "Layer chicken, fried onions, and rice in a pot.",
      "Sprinkle saffron water and chopped coriander.",
      "Cover and cook on low heat for 20 minutes.",
      "Serve hot with raita.",
    ],
  },
  {
    name: "Sushi Rolls",
    cuisine: "Japanese",
    image: "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    ingredients: [
      "2 cups sushi rice",
      "1/2 cup rice vinegar",
      "200g raw salmon",
      "1 sheet nori (seaweed)",
      "1 cucumber (julienned)",
      "Soy sauce",
      "Wasabi",
    ],
    instructions: [
      "Cook sushi rice and mix with rice vinegar.",
      "Lay nori on a bamboo mat and spread rice evenly.",
      "Place salmon and cucumber strips on rice.",
      "Roll tightly and slice into pieces.",
      "Serve with soy sauce and wasabi.",
    ],
  },
  {
    name: "Ramen",
    cuisine: "Japanese",
    image: "https://www.themealdb.com/images/media/meals/2ut3lp1618576879.jpg",
    ingredients: [
      "200g ramen noodles",
      "2 boiled eggs",
      "100g pork slices",
      "1 tbsp miso paste",
      "1 tbsp soy sauce",
      "1 tsp sesame oil",
      "Chopped green onions",
    ],
    instructions: [
      "Cook ramen noodles as per instructions.",
      "Prepare broth by boiling water with miso paste, soy sauce, and sesame oil.",
      "Add cooked noodles and pork slices to the broth.",
      "Garnish with boiled eggs and green onions.",
      "Serve hot.",
    ],
  },
  {
    name: "Pasta Carbonara",
    cuisine: "Italian",
    image: "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    ingredients: [
      "200g spaghetti",
      "2 eggs",
      "100g pancetta (diced)",
      "1/2 cup parmesan cheese",
      "Salt to taste",
      "Black pepper",
    ],
    instructions: [
      "Boil spaghetti until al dente, drain and set aside.",
      "Cook pancetta in a pan until crispy.",
      "Whisk eggs with parmesan cheese.",
      "Mix hot pasta with egg mixture and pancetta.",
      "Season with salt and black pepper, serve immediately.",
    ],
  },
  {
    name: "Margherita Pizza",
    cuisine: "Italian",
    image: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    ingredients: [
      "1 pizza base",
      "1/2 cup tomato sauce",
      "100g mozzarella cheese",
      "Fresh basil leaves",
      "Olive oil",
    ],
    instructions: [
      "Preheat oven to 220°C.",
      "Spread tomato sauce on pizza base.",
      "Add mozzarella cheese and fresh basil leaves.",
      "Drizzle olive oil over the pizza.",
      "Bake for 12-15 minutes until crust is golden brown.",
      "Serve hot.",
    ],
  },
  {
    name: "Tacos",
    cuisine: "Mexican",
    image: "https://www.themealdb.com/images/media/meals/uqtrww1441557733.jpg",
    ingredients: [
      "4 small tortillas",
      "200g ground beef",
      "1 tomato (diced)",
      "Lettuce (chopped)",
      "Shredded cheese",
      "Sour cream",
    ],
    instructions: [
      "Cook ground beef in a pan with salt and spices.",
      "Warm tortillas in a dry pan.",
      "Fill each tortilla with beef, tomato, lettuce, and cheese.",
      "Top with sour cream and serve.",
    ],
  },
  {
    name: "Pad Thai",
    cuisine: "Thai",
    image: "https://www.themealdb.com/images/media/meals/uxwuuy1515902672.jpg",
    ingredients: [
      "200g rice noodles",
      "100g shrimp",
      "2 eggs",
      "1/4 cup peanuts (crushed)",
      "1 tbsp fish sauce",
      "1 lime",
    ],
    instructions: [
      "Soak rice noodles in warm water until soft.",
      "Stir-fry shrimp and eggs in a pan.",
      "Add noodles, fish sauce, and peanuts.",
      "Squeeze lime juice over and serve hot.",
    ],
  },
  {
    name: "Pho",
    cuisine: "Vietnamese",
    image: "https://www.themealdb.com/images/media/meals/rrtssw1511798785.jpg",
    ingredients: [
      "200g rice noodles",
      "100g beef (thinly sliced)",
      "4 cups beef broth",
      "1 star anise",
      "1 cinnamon stick",
      "Bean sprouts",
      "Fresh basil",
    ],
    instructions: [
      "Boil beef broth with star anise and cinnamon.",
      "Cook rice noodles and place in a bowl.",
      "Add raw beef slices to hot broth.",
      "Top with bean sprouts and basil.",
      "Serve hot.",
    ],
  },
  {
    name: "Shakshuka",
    cuisine: "Middle Eastern",
    image: "https://www.themealdb.com/images/media/meals/g373701551450225.jpg",
    ingredients: [
      "2 eggs",
      "1 can diced tomatoes",
      "1 bell pepper (chopped)",
      "1 onion (chopped)",
      "2 garlic cloves (minced)",
      "1 tsp cumin",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Sauté onion, garlic, and bell pepper in a pan until soft.",
      "Add diced tomatoes, cumin, salt, and pepper, simmer for 10 minutes.",
      "Make small wells in the sauce and crack eggs into them.",
      "Cover and cook until eggs are set.",
      "Serve hot with bread.",
    ],
  },
  {
    name: "Falafel",
    cuisine: "Middle Eastern",
    image: "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
    ingredients: [
      "1 cup chickpeas (soaked overnight)",
      "1 small onion (chopped)",
      "2 garlic cloves",
      "1 tsp cumin",
      "1 tsp coriander",
      "Salt to taste",
      "Oil for frying",
    ],
    instructions: [
      "Blend chickpeas, onion, garlic, and spices into a coarse paste.",
      "Shape into small balls and refrigerate for 30 minutes.",
      "Heat oil in a pan and deep fry until golden brown.",
      "Serve with pita bread and tahini sauce.",
    ],
  },
  {
    name: "Miso Soup",
    cuisine: "Japanese",
    image: "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    ingredients: [
      "4 cups dashi broth",
      "2 tbsp miso paste",
      "100g tofu (cubed)",
      "1 green onion (chopped)",
      "1 sheet seaweed",
    ],
    instructions: [
      "Heat dashi broth in a pot.",
      "Dissolve miso paste in a small bowl with warm broth, then add back to pot.",
      "Add tofu and seaweed, simmer for 5 minutes.",
      "Garnish with green onions and serve hot.",
    ],
  },
  {
    name: "Kimchi",
    cuisine: "Korean",
    image: "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    ingredients: [
      "1 Napa cabbage",
      "1/4 cup salt",
      "4 cups water",
      "1 carrot (julienned)",
      "2 green onions (chopped)",
      "3 tbsp chili powder",
      "1 tbsp ginger (grated)",
      "1 tbsp garlic (minced)",
      "2 tbsp fish sauce",
    ],
    instructions: [
      "Cut cabbage and soak in saltwater for 2 hours.",
      "Rinse and drain thoroughly.",
      "Mix carrot, green onions, chili powder, ginger, garlic, and fish sauce in a bowl.",
      "Massage spice mix into cabbage.",
      "Pack into a jar and let ferment for at least 3 days.",
      "Store in the fridge and serve as needed.",
    ],
  },
  {
    name: "Peking Duck",
    cuisine: "Chinese",
    image: "https://www.themealdb.com/images/media/meals/063qsc1517729877.jpg",
    ingredients: [
      "1 whole duck",
      "2 tbsp honey",
      "2 tbsp soy sauce",
      "1 tbsp five-spice powder",
      "1 tbsp vinegar",
      "Pancakes for serving",
      "Cucumber (julienned)",
      "Spring onions (sliced)",
      "Hoisin sauce",
    ],
    instructions: [
      "Rub duck with five-spice powder and let it marinate for 2 hours.",
      "Brush with honey, soy sauce, and vinegar mixture.",
      "Roast in oven at 180°C for 1.5 hours until crispy.",
      "Carve the duck and serve with pancakes, cucumber, onions, and hoisin sauce.",
    ],
  },
  {
    name: "Paella",
    cuisine: "Spanish",
    image: "https://www.themealdb.com/images/media/meals/1520081754.jpg",
    ingredients: [
      "2 cups Arborio rice",
      "300g seafood mix (shrimp, mussels, squid)",
      "1 bell pepper (sliced)",
      "2 tomatoes (chopped)",
      "1/2 cup peas",
      "4 cups chicken broth",
      "1 tsp saffron",
      "1 tsp paprika",
      "Olive oil",
    ],
    instructions: [
      "Heat olive oil in a large pan.",
      "Sauté bell peppers and tomatoes.",
      "Add rice, saffron, paprika, and broth, simmer for 15 minutes.",
      "Add seafood and peas, cook until seafood is done.",
      "Let it rest for 5 minutes before serving.",
    ],
  },
  {
    name: "Churros",
    cuisine: "Spanish",
    image: "https://www.themealdb.com/images/media/meals/3dq7m31528716289.jpg",
    ingredients: [
      "1 cup water",
      "1 cup flour",
      "2 tbsp butter",
      "1 tbsp sugar",
      "1/2 tsp salt",
      "Oil for frying",
      "Cinnamon sugar for coating",
    ],
    instructions: [
      "Boil water with butter, sugar, and salt.",
      "Add flour and stir until dough forms.",
      "Pipe dough into hot oil and fry until golden.",
      "Roll in cinnamon sugar and serve with chocolate sauce.",
    ],
  },
  {
    name: "Greek Salad",
    cuisine: "Greek",
    image: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    ingredients: [
      "1 cucumber (chopped)",
      "1 tomato (chopped)",
      "1/2 red onion (sliced)",
      "1/2 cup feta cheese",
      "1/4 cup olives",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Combine cucumber, tomato, onion, and olives in a bowl.",
      "Drizzle with olive oil, salt, and pepper.",
      "Top with feta cheese and serve fresh.",
    ],
  },
  {
    name: "Beef Stroganoff",
    cuisine: "Russian",
    image: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    ingredients: [
      "400g beef (sliced)",
      "1 onion (chopped)",
      "1 cup mushrooms (sliced)",
      "1 cup sour cream",
      "1 tbsp mustard",
      "1 tbsp butter",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Sauté onion and mushrooms in butter.",
      "Add beef slices and cook until browned.",
      "Stir in mustard and sour cream, simmer for 10 minutes.",
      "Serve with rice or pasta.",
    ],
  },
  {
    name: "Tom Yum Soup",
    cuisine: "Thai",
    image: "https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg",
    ingredients: [
      "4 cups chicken broth",
      "200g shrimp",
      "1 lemongrass stalk (chopped)",
      "1 tbsp fish sauce",
      "1 lime",
      "Chili flakes",
    ],
    instructions: [
      "Boil chicken broth with lemongrass and chili flakes.",
      "Add shrimp and cook for 5 minutes.",
      "Stir in fish sauce and lime juice.",
      "Serve hot.",
    ],
  },
  {
    name: "Clam Chowder",
    cuisine: "American",
    image: "https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg",
    ingredients: [
      "2 cups clams",
      "2 potatoes (chopped)",
      "1 onion (chopped)",
      "2 cups milk",
      "2 tbsp butter",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Sauté onion in butter until translucent.",
      "Add potatoes and cook for 5 minutes.",
      "Pour in milk and bring to a simmer.",
      "Add clams and cook for another 5 minutes.",
      "Season and serve hot.",
    ],
  },
  {
    name: "Mango Sticky Rice",
    cuisine: "Thai",
    image: "https://www.themealdb.com/images/media/meals/uryqru1511798039.jpg",
    ingredients: [
      "1 cup sticky rice",
      "1 ripe mango (sliced)",
      "1 cup coconut milk",
      "2 tbsp sugar",
      "Pinch of salt",
    ],
    instructions: [
      "Cook sticky rice until soft.",
      "Heat coconut milk with sugar and salt until warm.",
      "Mix half of the coconut milk with the rice.",
      "Serve rice with mango slices and drizzle with remaining coconut milk.",
    ],
  },
  {
    name: "Shepherd’s Pie",
    cuisine: "British",
    image: "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    ingredients: [
      "500g ground lamb",
      "1 onion (chopped)",
      "2 carrots (chopped)",
      "1/2 cup peas",
      "2 cups mashed potatoes",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook lamb, onion, and carrots in a pan until browned.",
      "Add peas and season with salt and pepper.",
      "Spread mixture in a baking dish and top with mashed potatoes.",
      "Bake at 180°C for 20 minutes until golden brown.",
    ],
  },
  {
    name: "French Onion Soup",
    cuisine: "French",
    image: "https://www.themealdb.com/images/media/meals/xvrrux1511783685.jpg",
    ingredients: [
      "4 onions (sliced)",
      "4 cups beef broth",
      "2 tbsp butter",
      "1 tsp thyme",
      "1 baguette (sliced)",
      "1/2 cup grated cheese",
    ],
    instructions: [
      "Sauté onions in butter until caramelized.",
      "Add thyme and beef broth, simmer for 20 minutes.",
      "Ladle soup into bowls and top with baguette slices and cheese.",
      "Broil until cheese is melted and serve hot.",
    ],
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_CONNECTION_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    await Recipe.deleteMany();
    await Recipe.insertMany(recipes);

    console.log("✅ Database seeded successfully!");
    mongoose.connection.close();
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    mongoose.connection.close();
  }
}

seedDatabase();
